import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const directory = dirname(fileURLToPath(import.meta.url));
const output = resolve(directory, "../../skills/architecture-decision-authoring/scripts/vendor");
await mkdir(output, { recursive: true });
await build({
  absWorkingDir: directory,
  entryPoints: ["parser-entry.mjs"],
  outfile: resolve(output, "markdown-it.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: true,
  legalComments: "inline",
  banner: { js: "// Generated by tools/markdown-parser/build.mjs; markdown-it 15.0.2. See THIRD-PARTY-NOTICES.txt." }
});
await build({
  absWorkingDir: directory,
  entryPoints: ["json-entry.mjs"],
  mainFields: ["module", "main"],
  outfile: resolve(output, "jsonc-parser.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: true,
  legalComments: "inline",
  banner: { js: "// Generated by tools/markdown-parser/build.mjs; jsonc-parser 3.3.1. See THIRD-PARTY-NOTICES.txt." }
});

// Full upstream notices accompany the copy-only runtime bundle. Build tools
// are also recorded, even though esbuild itself is not distributed in it.
const packages = [
  ["markdown-it", "LICENSE"], ["entities", "LICENSE"],
  ["linkify-it", "LICENSE"], ["mdurl", "LICENSE"],
  ["punycode.js", "LICENSE-MIT.txt"], ["uc.micro", "LICENSE.txt"],
  ["esbuild", "LICENSE.md"], ["jsonc-parser", "LICENSE.md"]
];
let notices = "Third-party parser bundles and build-tool notices\n\n";
for (const [name, licenseFile] of packages) {
  const packageRoot = resolve(directory, "node_modules", name);
  const metadata = JSON.parse(await readFile(resolve(packageRoot, "package.json"), "utf8"));
  notices += `===== ${name} ${metadata.version} (${metadata.license}) =====\n`;
  notices += (await readFile(resolve(packageRoot, licenseFile), "utf8")).replace(/\r\n/g, "\n");
  notices += "\n\n";
}
await writeFile(resolve(output, "THIRD-PARTY-NOTICES.txt"), notices.trimEnd() + "\n");
